name: rp-env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - opencv-python==4.13.0.90
      - pandas==2.3.3
      - pdfminer-six==20251230
      - pdfplumber==0.11.9
      - pillow==12.1.0
      - pycparser==2.23
      - pyparsing==3.3.1
      - pypdfium2==5.3.0
      - pytz==2025.2
      - sympy==1.14.0
      - torch==2.10.0
      - torchvision==0.25.0
      - tqdm==4.67.3
      - tzdata==2025.3
